# Generated by Django 5.2 on 2025-06-30 14:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('estado_civil', models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)')], max_length=20, verbose_name='Estado Civil')),
                ('telefone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato: (XX) XXXX-XXXX ou (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')], verbose_name='Telefone')),
                ('endereco', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('profissao', models.CharField(blank=True, max_length=150, verbose_name='Profissão')),
                ('nivel_escolar', models.CharField(blank=True, choices=[('fundamental_incompleto', 'Ensino Fundamental Incompleto'), ('fundamental_completo', 'Ensino Fundamental Completo'), ('medio_incompleto', 'Ensino Médio Incompleto'), ('medio_completo', 'Ensino Médio Completo'), ('superior_incompleto', 'Ensino Superior Incompleto'), ('superior_completo', 'Ensino Superior Completo'), ('pos_graduacao', 'Pós-graduação'), ('nao_informar', 'Não desejo informar')], max_length=30, verbose_name='Nível Escolar')),
                ('data_conversao', models.DateField(blank=True, null=True, verbose_name='Data de Conversão')),
                ('membro_congregacao', models.BooleanField(default=False, verbose_name='Membro de Congregação?')),
                ('qual_congregacao', models.CharField(blank=True, help_text='Preencher apenas se for membro de congregação', max_length=150, verbose_name='Qual Congregação?')),
                ('aceito_por', models.CharField(blank=True, choices=[('batismo', 'Batismo'), ('aclamacao', 'Aclamação')], max_length=20, verbose_name='Aceito por')),
                ('frequenta_escola_biblica', models.BooleanField(default=False, verbose_name='Frequenta alguma classe da Escola Bíblica?')),
                ('qual_classe_escola_biblica', models.CharField(blank=True, help_text='Preencher apenas se frequenta a Escola Bíblica', max_length=100, verbose_name='Qual classe?')),
                ('papel', models.CharField(choices=[('congregado', 'Congregado'), ('membro', 'Membro'), ('secretario', 'Secretário')], default='congregado', max_length=20, verbose_name='Papel no Sistema')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ativo', models.BooleanField(default=True, verbose_name='Usuário Ativo')),
                ('aprovado', models.BooleanField(default=False, verbose_name='Cadastro Aprovado')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_aprovados', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['nome_completo'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
