# Generated by Django 5.2 on 2025-07-04 14:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aceito_por',
        ),
        migrations.AddField(
            model_name='user',
            name='alergias_texto',
            field=models.TextField(blank=True, verbose_name='Quais alergias?'),
        ),
        migrations.AddField(
            model_name='user',
            name='batizado_aguas',
            field=models.BooleanField(default=False, verbose_name='É batizado nas águas?'),
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve conter 11 dígitos, sem pontos ou traços.', regex='^\\d{11}$')], verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='user',
            name='data_batismo',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Batismo'),
        ),
        migrations.AddField(
            model_name='user',
            name='data_casamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Casamento'),
        ),
        migrations.AddField(
            model_name='user',
            name='deseja_exercer_funcao',
            field=models.BooleanField(default=False, verbose_name='Deseja exercer alguma função na 2ª IBCA?'),
        ),
        migrations.AddField(
            model_name='user',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_fotos/', verbose_name='Foto do Perfil'),
        ),
        migrations.AddField(
            model_name='user',
            name='local_batismo',
            field=models.CharField(blank=True, choices=[('2ibca', 'Na 2ª IBCA'), ('outra', 'Em Outra Igreja')], max_length=10, verbose_name='Onde foi o batismo?'),
        ),
        migrations.AddField(
            model_name='user',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=150, verbose_name='Natural da cidade de'),
        ),
        migrations.AddField(
            model_name='user',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome do Cônjuge'),
        ),
        migrations.AddField(
            model_name='user',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='user',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome do Pai'),
        ),
        migrations.AddField(
            model_name='user',
            name='outra_igreja_batismo',
            field=models.CharField(blank=True, help_text='Nome da igreja onde foi batizado', max_length=200, verbose_name='Qual igreja?'),
        ),
        migrations.AddField(
            model_name='user',
            name='qual_funcao_deseja',
            field=models.TextField(blank=True, verbose_name='Qual função ou ministério?'),
        ),
        migrations.AddField(
            model_name='user',
            name='recebido_por_aclamacao',
            field=models.BooleanField(default=False, verbose_name='Foi recebido por aclamação na 2ª IBCA?'),
        ),
        migrations.AddField(
            model_name='user',
            name='rg',
            field=models.CharField(blank=True, max_length=20, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='user',
            name='tem_alergia_medicacao',
            field=models.BooleanField(default=False, verbose_name='Possui alergia a alguma medicação?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='membro_congregacao',
            field=models.BooleanField(default=False, verbose_name='É membro de alguma congregação?'),
        ),
        migrations.CreateModel(
            name='Filho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome do Filho(a)')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Filho',
                'verbose_name_plural': 'Filhos',
                'ordering': ['data_nascimento'],
            },
        ),
    ]
