# Generated by Django 5.2 on 2025-05-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_youtube', models.URLField(help_text='URL do vídeo do YouTube que será exibido na página principal', max_length=255, verbose_name='Link do YouTube')),
                ('titulo_video', models.CharField(default='Última Transmissão ao Vivo', help_text='Título que será exibido acima do vídeo', max_length=100, verbose_name='Título do Vídeo')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
