# Generated by Django 5.2 on 2025-05-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='imagem_personalizada',
            field=models.ImageField(blank=True, help_text="Faça upload de uma imagem personalizada (apenas se 'Tipo de Imagem' for 'Imagem Personalizada')", null=True, upload_to='uploads/capas/', verbose_name='Imagem Personalizada'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='tipo_imagem',
            field=models.CharField(choices=[('capa-ceia', 'Culto de Ceia'), ('capa-divino', 'Culto Divino'), ('capa-ebd', 'EBD'), ('capa-maravilhas', 'Culto das Maravilhas'), ('capa-louvor', 'Culto de Louvor'), ('personalizada', 'Imagem Personalizada (Upload)')], default='capa-maravilhas', help_text="Selecione uma imagem padrão ou escolha 'Imagem Personalizada' para fazer upload", max_length=20, verbose_name='Tipo de Imagem'),
        ),
    ]
