# Generated by Django 5.2 on 2025-05-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_configuracaosite_imagem_personalizada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Departamento')),
                ('descricao', models.TextField(blank=True, help_text='Uma breve descrição do departamento.', verbose_name='Descrição')),
                ('imagem', models.ImageField(help_text='Imagem representativa do departamento.', upload_to='departamentos/', verbose_name='Imagem')),
                ('categoria', models.CharField(choices=[('TREINAMENTO', 'Ministério de Treinamento e Crescimento Cristão'), ('MUSICA', 'Ministério de Música')], max_length=50, verbose_name='Ministério Principal')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição dentro do ministério (menor número aparece primeiro).', verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['categoria', 'ordem'],
            },
        ),
    ]
