# Generated by Django 5.2 on 2025-06-10 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecaoLideranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Seção')),
                ('descricao', models.TextField(blank=True, verbose_name='Texto de Descrição')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição na página (menor número aparece primeiro).')),
            ],
            options={
                'verbose_name': 'Seção de Liderança',
                'verbose_name_plural': 'Seções de Liderança',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo ou Função')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('foto', models.ImageField(upload_to='lideranca/', verbose_name='Foto')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição dentro da seção.')),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='home.secaolideranca')),
            ],
            options={
                'verbose_name': 'Pessoa da Liderança',
                'verbose_name_plural': 'Pessoas da Liderança',
                'ordering': ['ordem'],
            },
        ),
    ]
