# Generated by Django 5.2 on 2025-06-13 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_secaolideranca_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], unique=True, verbose_name='Dia da Semana')),
                ('resumo', models.CharField(max_length=100, verbose_name='Resumo (ex: Dia de celebração)')),
                ('icone', models.CharField(help_text="Nome do ícone (ex: 'celebracao', 'oracao'). Use o nome do arquivo sem a extensão.", max_length=50, verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Dia da Semana',
                'verbose_name_plural': 'Dias da Semana',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EventoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('periodo', models.CharField(max_length=50, verbose_name='Período (ex: 15-17 Julho)')),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Evento Especial',
                'verbose_name_plural': 'Eventos Especiais',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('horario', models.TimeField()),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='home.diasemana')),
            ],
            options={
                'verbose_name': 'Evento da Semana',
                'verbose_name_plural': 'Eventos da Semana',
                'ordering': ['horario'],
            },
        ),
    ]
